POST http://localhost:3003/users
Content-Type: application/json

{
    "name": "Michael Silva",
    "cpf": 10320802485,
    "birthDate": "27/10/1994"
}


###
GET http://localhost:3003/users
Content-Type: application/json

###
GET http://localhost:3003/users/10291540406
Content-Type: application/json